AY-9
Soffietto/Khayrullin_Java_2016 pull request #4
Opened 2016-11-16 19:33 UTC by Soffietto

2016-11-16 20:14 UTC, GoodBoy962 reviewed
названия папок с маленьких букв. Цепочку у Марата взял видимо. Сам паттерн реализован. Но он не выполняет то, что должен. Посмотри gist, как он выводит. У вас с Маратом в проверке, надо ли выводить это сообщение сейчас, ошибка.

2016-11-16 20:14 UTC, GoodBoy962 commented on [AY-9]Homework/pom.xml
> +                    <source>1.8</source>
в проперти

2016-11-16 20:14 UTC, GoodBoy962 commented on [AY-9]Homework/pom.xml
> +    <groupId>com.jetbrainslab.homework.khayrullin</groupId>
homework убери

2016-11-16 20:14 UTC, GoodBoy962 commented on [AY-9]Homework/src/main/java/com/khayrullin/ReaderHW/LowerToUpperAndUppertToLowerReader.java
> +    protected LowerToUpperAndUppertToLowerReader(Reader in) {
Uppert

2016-11-17 13:26 UTC, GoodBoy962 commented on [AY-9]Homework/src/main/java/com/khayrullin/loggerHW/ErrorLogger.java
> +package com.khayrullin.loggerHW;
без постфикса HW смысловая нагрузка поменяется?

2016-11-17 13:26 UTC, GoodBoy962 commented on [AY-9]Homework/src/main/java/com/khayrullin/loggerHW/InfoLogger.java
> +        if (level.equals("[INFO]") || level.equals("[ERROR]")) {
вместе с Лией делали? тогда прочитай ее коммент

2016-11-17 13:26 UTC, GoodBoy962 commented on [AY-9]Homework/src/main/java/com/khayrullin/loggerHW/WarnLogger.java
> +        System.out.println(message);
везде реализован одинаково. Наверное что-то не так, не думаешь?

2016-11-17 13:26 UTC, GoodBoy962 commented on [AY-9]Homework/src/main/java/com/khayrullin/readerHW/Main.java
> +        File file = new File("src/main/java/com/khayrullin/readerHW/file.txt");
у одного тебя работает

2016-11-17 16:55 UTC, GoodBoy962 commented on [AY-9]Homework/src/main/java/com/khayrullin/logger/WarnLogger.java
> +        String[] s = message.split(" : ");
[WARN] : [warning : ] не проходит полностью
[WARN] : [warning  не должно проходить

2016-11-17 16:55 UTC, GoodBoy962 commented on [AY-9]Homework/src/main/java/com/khayrullin/reader/Main.java
> +        File file = new File("[AY-9]Homework/src/main/java/com/khayrullin/reader/file.txt");
спроси Марата как делать)

2016-11-17 16:55 UTC, GoodBoy962 commented on [AY-9]Homework/src/main/java/com/khayrullin/logger/WarnLogger.java
> +        if (level.equals("[WARN]")) {
через enum

2016-11-17 16:55 UTC, GoodBoy962 commented on [AY-9]Homework/src/main/java/com/khayrullin/logger/Logger.java
> +    void writeMessage(String message){
не замечаешь то, что writeMessage везде одинаковый? может тогда пусть будет один в родительском классе

2016-11-17 16:55 UTC, GoodBoy962 commented on [AY-9]Homework/src/main/java/com/khayrullin/logger/InfoLogger.java
> +        if (level.equals("[INFO]") || level.equals("[ERROR]")) {
enum

2016-11-17 16:55 UTC, GoodBoy962 commented on [AY-9]Homework/src/main/java/com/khayrullin/logger/InfoLogger.java
> +
пустую строку можно убрать

2016-11-17 16:55 UTC, GoodBoy962 commented on [AY-9]Homework/src/main/java/com/khayrullin/logger/ErrorLogger.java
> +        if (level.equals("[ERROR]")) {
enum

2016-11-17 19:34 UTC, Soffietto commented on [AY-9]Homework/src/main/java/com/khayrullin/logger/Logger.java
> +    void writeMessage(String message){
Он и так в родительском классе

2016-11-17 20:00 UTC, Soffietto commented
Вот щас вообще бомба должна быть!

2016-11-19 10:47 UTC, GoodBoy962 reviewed
оценки вас с Дамиром пополам?

2016-11-19 10:47 UTC, GoodBoy962 commented on [AY-9]Homework/src/main/java/com/khayrullin/logger/ErrorLogger.java
> +        this.regularExpression = "\\[ERROR\\] : (?<message>\\[.+\\])$";
не нравится мне. Можно передать только уровень и через мутатор(сеттер)

2016-11-19 10:47 UTC, GoodBoy962 commented on [AY-9]Homework/src/main/java/com/khayrullin/logger/InfoLogger.java
> +        this.regularExpression = "\\[(INFO|ERROR)\\] : (?<message>\\[.+\\])$";
аналогично

2016-11-19 10:47 UTC, GoodBoy962 commented on [AY-9]Homework/src/main/java/com/khayrullin/logger/Logger.java
> +    protected String regularExpression;
private и set

2016-11-19 11:54 UTC, Soffietto commented
Вот щас точно бомба!

2016-11-19 13:54 UTC, GoodBoy962 reviewed
логгер работает неверно

2016-11-19 13:54 UTC, GoodBoy962 commented on [AY-9]Homework/src/main/java/com/khayrullin/logger/Main.java
> +    public static void main(String[] args) {
вывод неправильный у тебя.

2016-11-19 14:04 UTC, Soffietto commented
Вот щас верно

2016-11-19 14:48 UTC, GoodBoy962 reviewed
почти

2016-11-19 14:48 UTC, GoodBoy962 commented on [AY-9]Homework/src/main/java/com/khayrullin/logger/ErrorLogger.java
> +        this.setLevel(Level.ERROR.toString());
this.setLevel(...toString) ??????? очень трудная конструкция. достаточно передать Level.ERROR

2016-11-19 14:48 UTC, GoodBoy962 commented on [AY-9]Homework/src/main/java/com/khayrullin/logger/Logger.java
> +        Pattern pattern = Pattern.compile("\\[(" + level + ")\\] : (?<message>\\[.+\\])$");
если вынести в конструктор, будет вызываться только 1 раз, а так по количеству сообщений

2016-11-20 19:08 UTC, GoodBoy962 reviewed
почти готово

2016-11-20 19:08 UTC, GoodBoy962 commented on [AY-9]Homework/src/main/java/com/khayrullin/logger/ErrorLogger.java
> +        this.setLevel(Level.ERROR);
а без this не сработает?

2016-11-20 19:08 UTC, GoodBoy962 commented on [AY-9]Homework/src/main/java/com/khayrullin/logger/Logger.java
> +        matcher =Pattern.compile("\\[(" + level + ")\\] : (?<message>\\[.+\\])$").matcher(message);
Pattern.compile("\\[(" + level + ")\\] : (?<message>\\[.+\\])$") выполняется n раз, где n-число сообщений. А можно только один раз

2016-11-20 20:16 UTC, Soffietto commented
Вот щас тооочно должно пройти!

2016-11-20 22:31 UTC, GoodBoy962 requested changes

2016-11-20 22:31 UTC, GoodBoy962 commented on [AY-9]Homework/src/main/java/com/khayrullin/logger/Logger.java
> +        this.pattern = Pattern.compile("\\[(" + level + ")\\] : (?<message>\\[.+\\])$");
setLevel означает this.level = level

2016-11-21 08:00 UTC, GoodBoy962 commented on [AY-9]Homework/src/main/java/com/khayrullin/logger/ErrorLogger.java
> +        setLevelPattern(Level.ERROR);
что насчет просто setLevel?

2016-11-21 08:02 UTC, GoodBoy962 commented on [AY-9]Homework/src/main/java/com/khayrullin/logger/ErrorLogger.java
> +        setLevelPattern(Level.ERROR);
исправишь, и будет все готово

2016-11-21 08:03 UTC, GoodBoy962 commented on [AY-9]Homework/src/main/java/com/khayrullin/logger/ErrorLogger.java
> +        setLevelPattern(Level.ERROR);
сам смержи после исправления

2016-11-21 08:32 UTC, merged